######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 1 18:34:39 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/readerview.h src/TxtReader.h
SOURCES += src/main.cpp src/readerview.cpp src/TxtReader.cpp
RESOURCES += txtreader.qrc
RC_FILE = myapp.rc
